### PR TITLE
Do not display "Secret" fields in plain text

### LINKED ISSUE #20: Secret fields are displayed in plain text
**Describe the bug**
When I enter the "Prod JWT Secret" and the "Authentication Secret" and save them, they are shown in plain text. This allows any user of the instance with access to the settings to just copy them out and use them for unwanted purposes.

**To Reproduce**
1. Enter secrets
2. Save
3. Secrets are visible

**Expected behavior**
I would expect that a "password" style field would be used for the secrets so they are not shown in the interface and cannot be copied out.

**Screenshots**

plugin-conf

### PR DESCRIPTION
**Pull request by biozshock**

### CODE REVIEW

**Comment by oltmanns-leuchtfeuer** [comment]
just tested it and it works just as intended. Both Secret are not shown as plain text anymore. :) 

image

**Review by luguenth — COMMENTED** [review]
on what basis did you change the codefixes? Is it mautic or leuchtfeuer codestyle? Or is it your own? @biozshock

**Comment by biozshock** [comment]
@luguenth  I did not change any codefixes, just upgraded to latest version.

**Comment by luguenth** [comment]
@biozshock please look at the codestyle again :)

**Comment by biozshock** [comment]
@luguenth master still contains a lot of style errors.

**Comment by elbebass** [comment]
@biozshock I have added the Mautic php-cs-fixer rules and fixed all files on master. Additional I updated the version of php-cs-fixer and added a reusable command to run php-cs-fixer locally before every commit.

https://github.com/Leuchtfeuer/mautic-deutschepost/blob/master/composer.json#L38

Just rune `composer cs-fix` before you commit and php-cs-fixer will apply the codestyle.

**Comment by stefanvetter** [comment]
We just downloaded and installed the latest version from the repo, but the secret fields are still displayed in plain text. What might have gone wrong?

**Comment by elbebass** [comment]
@stefanvetter not yet. There is still a unit test failing (https://github.com/Leuchtfeuer/mautic-deutschepost/pull/23). Waiting for @biozshock to fix it.

**Comment by stefanvetter** [comment]
@elbebass Alright, thanks for the feedback :)

**Pull request merged**
